export const API_KEY = process.env.REACT_APP_SPOONACULAR_API_KEY;

export const Ingredients_IMG_CDN = "https://spoonacular.com/cdn/ingredients_100x100/";

export const mealType = [{name:"main course",want:false},
    {name:"side dish",want:false},
    {name:"dessert",want:false},
    {name:"appetizer",want:false},
    {name:"salad",want:false},
    {name:"bread",want:false},
    {name:"breakfast",want:false},
    {name:"soup",want:false},
    {name:"beverage",want:false},
    {name:"sauce",want:false},
    {name:"marinade",want:false},
    {name:"fingerfood",want:false},
    {name:"snack",want:false},
    {name:"drink",want:false}];

export const intolerances = [{name:"Dairy",have:false},
    {name:"Egg",have:false},
    {name:"Gluten",have:false},
    {name:"Grain",have:false},
    {name:"Peanut",have:false},
    {name:"Seafood",have:false},
    {name:"Sesame",have:false},
    {name:"Shellfish",have:false},
    {name:"Soy",have:false},
    {name:"Sulfite",have:false},
    {name:"TreeNut",have:false},
    {name:"Wheat",have:false}];

export const cuisines = [{name:"African",want:false},
    {name:"Asian",want:false},
    {name:"American",want:false},
    {name:"British",want:false},
    {name:"Cajun",want:false},
    {name:"Caribbean",want:false},
    {name:"Chinese",want:false},
    {name:"Eastern European",want:false},
    {name:"European",want:false},
    {name:"French",want:false},
    {name:"German",want:false},
    {name:"Greek",want:false},
    {name:"Indian",want:false},
    {name:"Irish",want:false},
    {name:"Italian",want:false},
    {name:"Japanese",want:false},
    {name:"Jewish",want:false},
    {name:"Korean",want:false},
    {name:"Latin American",want:false},
    {name:"Mediterranean",want:false},
    {name:"Mexican",want:false},
    {name:"Middle Eastern",want:false},
    {name:"Nordic",want:false},
    {name:"Southern",want:false},
    {name:"Spanish",want:false},
    {name:"Thai",want:false},
    {name:"Vietnamese",want:false}];

export const sort = [{name:"popularity",want:false},
    {name:"healthiness",want:false},
    {name:"price",want:false},
    {name:"time",want:false},
    {name:"protein",want:false},
    {name:"caffeine",want:false},
    {name:"energy",want:false},
    {name:"calories",want:false},
    {name:"calcium",want:false},
    {name:"carbohydrates",want:false},
    {name:"carbs",want:false},
    {name:"cholesterol",want:false},
    {name:"total-fat",want:false},
    {name:"sugar",want:false},
    {name:"sodium",want:false},
    {name:"alcohol",want:false},
    {name:"fluoride",want:false},
    {name:"trans-fat",want:false},
    {name:"saturated-fat",want:false},
    {name:"mono-unsaturated-fat",want:false},
    {name:"poly-unsaturated-fat",want:false},
    {name:"fiber",want:false},
    {name:"iodine",want:false},
    {name:"iron",want:false},
    {name:"magnesium",want:false},
    {name:"manganese",want:false},
    {name:"vitamin-b3",want:false},
    {name:"vitamin-b5",want:false},
    {name:"pantothenic-acid",want:false},
    {name:"phosphorus",want:false},
    {name:"potassium",want:false},
    {name:"vitamin-b2",want:false},
    {name:"riboflavin",want:false},
    {name:"selenium",want:false},
    {name:"vitamin-b1",want:false},
    {name:"thiamin",want:false},
    {name:"vitamin-a",want:false},
    {name:"vitamin-b6",want:false},
    {name:"vitamin-b12",want:false},
    {name:"vitamin-c",want:false},
    {name:"vitamin-d",want:false},
    {name:"vitamin-e",want:false},
    {name:"vitamin-k",want:false},
    {name:"zinc",want:false}];

export const sortDirection = {name:"sortDirection",asc:true};

export const nutrientsInfo = [{name:"Carbs",isVisible:false,minVal:null,maxVal:null},
{name:"Protein",isVisible:false,minVal:null,maxVal:null},
{name:"Calories",isVisible:false,minVal:null,maxVal:null},
{name:"Fat",isVisible:false,minVal:null,maxVal:null},
{name:"Sugar",isVisible:false,minVal:null,maxVal:null},
{name:"Fiber",isVisible:false,minVal:null,maxVal:null},
{name:"Alcohol",isVisible:false,minVal:null,maxVal:null},
{name:"Caffeine",isVisible:false,minVal:null,maxVal:null},
{name:"Copper",isVisible:false,minVal:null,maxVal:null},
{name:"Calcium",isVisible:false,minVal:null,maxVal:null},
{name:"SaturatedFat",isVisible:false,minVal:null,maxVal:null},
{name:"Fluoride",isVisible:false,minVal:null,maxVal:null},
{name:"Cholesterol",isVisible:false,minVal:null,maxVal:null},
{name:"Sodium",isVisible:false,minVal:null,maxVal:null},
{name:"Selenium",isVisible:false,minVal:null,maxVal:null},
{name:"VitaminA",isVisible:false,minVal:null,maxVal:null},
{name:"VitaminB1",isVisible:false,minVal:null,maxVal:null},
{name:"VitaminB2",isVisible:false,minVal:null,maxVal:null},
{name:"VitaminB3",isVisible:false,minVal:null,maxVal:null},
{name:"VitaminB5",isVisible:false,minVal:null,maxVal:null},
{name:"VitaminB6",isVisible:false,minVal:null,maxVal:null},
{name:"VitaminB12",isVisible:false,minVal:null,maxVal:null},
{name:"VitaminC",isVisible:false,minVal:null,maxVal:null},
{name:"VitaminD",isVisible:false,minVal:null,maxVal:null},
{name:"VitaminE",isVisible:false,minVal:null,maxVal:null},
{name:"VitaminK",isVisible:false,minVal:null,maxVal:null},
{name:"Phosphorus",isVisible:false,minVal:null,maxVal:null},
{name:"Potassium",isVisible:false,minVal:null,maxVal:null},
{name:"Manganese",isVisible:false,minVal:null,maxVal:null},
{name:"Magnesium",isVisible:false,minVal:null,maxVal:null},
{name:"Iodine",isVisible:false,minVal:null,maxVal:null},
{name:"Zinc",isVisible:false,minVal:null,maxVal:null},
{name:"Iron",isVisible:false,minVal:null,maxVal:null},
{name:"Folate",isVisible:false,minVal:null,maxVal:null},
{name:"FolicAcid",isVisible:false,minVal:null,maxVal:null}];